project:
  type: book

book:
  title: "Les bonnes pratiques en R"
  author: "Réseau des référentes et référents R"
  date: "12/09/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - demarrer.qmd
    - renv.qmd
    - check_list.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-link: true
    code-copy: true
  pdf:
    documentclass: scrreprt

editor: visual